workspace:
  base: /go/src
  path: github.com/appleboy/drone-line

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: appleboy/golang-testing:1.9.1
    group: testing
    commands:
      - make vet
      - make lint
      - make test-vendor
      - make misspell-check

  test:
    image: appleboy/golang-testing:1.9.1
    group: testing
    secrets: [ line_to, line_channel_secret, line_channel_token ]
    commands:
      - make test
      - make coverage

  build_linux_amd64:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_i386:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_i386

  build_linux_arm64:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: appleboy/golang-testing:1.9.2
    pull: true
    group: build
    commands:
      - make build_linux_arm

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - coverage.txt
    when:
      event: [ push, pull_request ]

  release:
    image: appleboy/golang-testing:1.9.1
    commands:
      - make release
    when:
      event: [ tag ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: [ master ]

  github:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
